name: Deploy (Firebase Hosting)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup Firebase CLI (with token or service account)
        uses: w9jds/setup-firebase@main
        with:
          tools: hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          if [ -n "${GCP_SA_KEY}" ]; then
            echo "Using GCP_SA_KEY for auth"
            firebase deploy --only hosting
          elif [ -n "${FIREBASE_TOKEN}" ]; then
            echo "Using FIREBASE_TOKEN for auth"
            firebase deploy --only hosting
          else
            echo "No auth provided (GCP_SA_KEY or FIREBASE_TOKEN). Skipping deploy." && exit 0
          fi

